escenario:
    altopx: 200
    anchopx: 2000
    altoun: 500
    anchoun: 90	
    nivel_agua: 100
    imagen_tierra: imagenes/mascaras/mascara.png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: circ
          x: 25
          y: 50
          escala: 4
          color: FF0000
          rot: 0
          masa: 3
          estatico: no