escenario:
    altopx: 600
    anchopx: 800
    altoun: 250
    anchoun: 250
    nivel_agua: 20
    imagen_tierra: mascara (1).png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: tri
          x: 250
          y: 250
          escala: 5
          color: FF0000
          rot: 45
          masa: 3
          estatico: no