escenario:
    altopx: 600
    anchopx: 800
    altoun: 300
    anchoun: 400
    nivel_agua: 10
    imagen_tierra: imagenes/mascaras/mascara1.png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: circ
          x: 44
          y: 250
          ancho: 10
          alto: 12
          color: FF0000
          rot: 0
          masa: 3
          estatico: no
          escala: 1