escenario:
    altopx: 668
    anchopx: 1266
    altoun: 60
    anchoun: 120
    nivel_agua: 5
    maximosclientes: 2
    imagen_tierra: imagenes/mascaras/mascara1.png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: rect
          x: 50
          y: 50
          ancho: 5
          alto: 8
          color: FF0000
          rot: 0
          masa: 10
          estatico: no
        - tipo: rect
          x: 30
          y: 50
          ancho: 5
          alto: 8
          color: FF0000
          rot: 0
          masa: 10
          estatico: no