escenario:
    altopx: 600
    anchopx: 600
    altoun: 250
    anchoun: 250
    nivel_agua: 50
    imagen_tierra: mascara (1).png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: rect
          x: 56
          y: 200
          escala: 4
          color: FF0000
          rot: 0
          masa: 30
          estatico: no          
        - tipo: circ
          x: 12
          y: 200
          escala: 4
          color: FF04FF
          rot: 10
          masa: 3000
          estatico: no
        - tipo: circ
          x: 90
          y: 240
          escala: 4
          color: FF0000
          rot: 0
          masa: 30
          estatico: no
        - tipo: circ
          x: 100
          y: 240
          escala: 4
          color: FF0000
          rot: 0
          masa: 30
          estatico: no            