escenario:
    altopx: 600
    anchopx: 800
    altoun: 300
    anchoun: 750
    nivel_agua: 100
    imagen_tierra: imagenes/mascaras/mascara1.png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: rect
          x: 500
          y: 250
          ancho: 10
          alto: 10
          color: FF0000
          rot: 0
          masa: 3
          estatico: no
          