escenario:
    altopx: 600
    anchopx: 600
    altoun: 100
    anchoun: 100
    nivel_agua: 90
    imagen_tierra: mascara1.png
    imagen_cielo: cielo.png
    objetos:
        - tipo: rect
          x: 20
          y: 45
          ancho: 3
          alto: 3
          color: 00FF00
          rot: 0
          masa: 20
          estatico: no