escenario:
    altopx: 600
    anchopx: 600
    altoun: 100
    anchoun: 100
    nivel_agua: 60
    imagen_tierra: mascara (1).png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: circ
          x: 45
          y: 0
          escala: 4
          color: FF0000
          rot: 0
          masa: 20
          estatico: no
        - tipo: rect
          x: 10
          y: 3
          ancho: 3
          alto: 3
          color: 00FF00
          rot: 0
          masa: 2000
          estatico: no
        - tipo: rect
          x: 18
          y: 90
          ancho: 3
          alto: 3
          color: 00FF00
          rot: 0
          masa: 20
          estatico: no