escenario:
    altopx: 500
    anchopx: 500
    altoun: 150
    anchoun: 150	
    nivel_agua: 100
    imagen_tierra: imagenes/mascaras/mascara.png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: circ
          x: 150.9
          y: 75.3
          escala: 4
          color: FF0000
          rot: 0
          masa: 3
          estatico: no
        - tipo: cuad
          x: 25.5
          y: 220
          escala: 5
          color: FF8888
          rot: 45
          masa: 3
          estatico: no
        - tipo: cuad
          x: 320
          y: 220
          escala: 5
          color: FF8888
          rot: 45
          masa: 3
          estatico: no
        - tipo: cuad
          x: 60
          y: 145
          escala: 5
          color: FF8888
          rot: 45
          masa: 3
          estatico: no