escenario:
    altopx: 600
    anchopx: 600
    altoun: 100
    anchoun: 100
    nivel_agua: 50
    imagen_tierra: mascara (1).png
    imagen_cielo: imagenes/texturas/cielo.png
    objetos:
        - tipo: circ
          x: 55
          y: 15
          escala: 4
          color: FF0000
          rot: 0
          masa: 20
          estatico: si
        - tipo: rect
          x: 54
          y: 8
          ancho: 50
          alto: 3
          color: 00FF00
          rot: 0
          masa: 20
          estatico: no