escenario:
    altopx: 800
    anchopx: 800
    altoun: 100
    anchoun: 250
    nivel_agua: 50
    imagen_tierra: mascara (1).png
    imagen_cielo: imagenes/texturas/nube1.png
    objetos:
        - tipo: circ
          x: 100
          y: 100
          escala: 10
          color: FF0000
          rot: 0
          masa: 3
          estatico: no